import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers as SessionProvider } from "@/components/providers/session-provider";
import { SWRProvider } from "@/components/providers/swr-provider";
import { Providers as ThemeProvider } from "@/components/providers/theme-provider"
import { TopBar } from "@/components/ui/topbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col">
        <SWRProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SessionProvider>
                <TopBar />
                <div className="flex-1 overflow-hidden">
                  {children}
                </div>
            </SessionProvider>
          </ThemeProvider>
        </SWRProvider>
      </body>
    </html>
  );
}
