import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers as SessionProvider } from "@/components/providers/session-providers";
import { Providers as ThemeProvider } from "@/components/providers/theme-provider"
import { TopBar } from "@/components/ui/topbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>
            <TopBar />
            <div className="px-16 sm:px-8 lg:px-14">
                {children}
            </div >
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
