"""update_engine_enum_to_use_backtestengine

Revision ID: 5db09d2bf389
Revises: 75e6d3abf16e
Create Date: 2025-06-12 00:33:17.118757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5db09d2bf389'
down_revision: Union[str, None] = '75e6d3abf16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the new enum type
    backtestengine_enum = postgresql.ENUM('LEAN', 'PLACEHOLDER', name='backtestengine')
    backtestengine_enum.create(op.get_bind())

    # Add a temporary column with the new enum type
    op.add_column('backtests', sa.Column('engine_new', sa.Enum('LEAN', 'PLACEHOLDER', name='backtestengine'), nullable=True))

    # Migrate data from old column to new column, mapping BACKTESTING -> PLACEHOLDER
    op.execute("""
        UPDATE backtests
        SET engine_new = CASE
            WHEN engine = 'LEAN' THEN 'LEAN'::backtestengine
            WHEN engine = 'BACKTESTING' THEN 'PLACEHOLDER'::backtestengine
            ELSE 'LEAN'::backtestengine
        END
    """)

    # Drop the old column
    op.drop_column('backtests', 'engine')

    # Rename the new column to the original name
    op.alter_column('backtests', 'engine_new', new_column_name='engine')

    # Drop the old enum type
    op.execute("DROP TYPE IF EXISTS backtest_status CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate the old enum type
    backtest_status_enum = postgresql.ENUM('LEAN', 'BACKTESTING', name='backtest_status')
    backtest_status_enum.create(op.get_bind())

    # Add a temporary column with the old enum type
    op.add_column('backtests', sa.Column('engine_old', postgresql.ENUM('LEAN', 'BACKTESTING', name='backtest_status'), nullable=True))

    # Migrate data back, mapping PLACEHOLDER -> BACKTESTING
    op.execute("""
        UPDATE backtests
        SET engine_old = CASE
            WHEN engine = 'LEAN' THEN 'LEAN'::backtest_status
            WHEN engine = 'PLACEHOLDER' THEN 'BACKTESTING'::backtest_status
            ELSE 'LEAN'::backtest_status
        END
    """)

    # Drop the new column
    op.drop_column('backtests', 'engine')

    # Rename the old column back
    op.alter_column('backtests', 'engine_old', new_column_name='engine')

    # Drop the new enum type
    op.execute("DROP TYPE IF EXISTS backtestengine CASCADE")
    # ### end Alembic commands ###
