"""update datetime fields to be non nullable with defaults

Revision ID: 75e6d3abf16e
Revises: a8805ad44213
Create Date: 2025-06-01 19:50:02.606833

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "75e6d3abf16e"
down_revision: Union[str, None] = "a8805ad44213"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # First, update existing NULL values with a default datetime
    from datetime import datetime, timezone

    default_datetime = datetime.now(timezone.utc)

    # Update NULL starting_date values
    op.execute(
        f"UPDATE backtests SET starting_date = '{default_datetime}' WHERE starting_date IS NULL"
    )

    # Update NULL ending_date values
    op.execute(
        f"UPDATE backtests SET ending_date = '{default_datetime}' WHERE ending_date IS NULL"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "backtests",
        "starting_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "backtests", "ending_date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "backtests", "ending_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "backtests",
        "starting_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    # ### end Alembic commands ###
