"""Added name, description, and date fields to Backtest

Revision ID: aa860ac57549
Revises: cf4dffe32e23
Create Date: 2025-05-26 10:19:54.170610

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa860ac57549"
down_revision: Union[str, None] = "cf4dffe32e23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "backtests",
        sa.Column(
            "name", sa.String(length=255), nullable=False, server_default="Default Name"
        ),
    )
    op.add_column("backtests", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("backtests", sa.Column("starting_date", sa.DateTime(), nullable=True))
    op.add_column("backtests", sa.Column("ending_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("backtests", "ending_date")
    op.drop_column("backtests", "starting_date")
    op.drop_column("backtests", "description")
    op.drop_column("backtests", "name")
    # ### end Alembic commands ###
