"""Added engine to order model

Revision ID: c79123002c43
Revises: c0b71c1f6a51
Create Date: 2025-06-20 23:05:46.089473

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c79123002c43"
down_revision: Union[str, None] = "c0b71c1f6a51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column(
        "orders",
        sa.Column(
            "engine",
            sa.Enum("LEAN", "PLACEHOLDER", name="backtestengine"),
            nullable=True,
        ),
    )

    # Set a default value for existing rows (using LEAN as default since it's the primary engine)
    op.execute("UPDATE orders SET engine = 'LEAN'")

    # Then make the column not nullable
    op.alter_column("orders", "engine", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "engine")
    # ### end Alembic commands ###
