name: Format Check

on:
  workflow_dispatch:
  pull_request:
    branches: ["*"]

jobs:
  frontend-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run Prettier check
        working-directory: ./frontend
        run: npm run style:check .
